### ISSUE TITLE
DbProviderFactories is not in netstandard2.0?

### ISSUE THREAD

**Issue by BryanWilhite** [BryanWilhite/Songhay.DataAccess#1]
@divega => [Bring System.Data.Common.DbProviderFactories into .NET Standard #356](https://github.com/dotnet/standard/issues/356)

@FransBouma => [Port over DbProviderFactories class #4571](https://github.com/dotnet/corefx/issues/4571)

@kkurni => [API for Code based configuration for DBProviderFactories #6476](https://github.com/dotnet/corefx/issues/6476)

Should this take forever consider `GodSharp.Data.Common.DbProvider` [[NuGet](https://www.nuget.org/packages/GodSharp.Data.Common.DbProvider/) preview]

**Comment by divega** [comment]
FYI, I updated the proposal today. See https://github.com/dotnet/corefx/issues/20903#issuecomment-341842353.

**Comment by BryanWilhite** [comment]
addressed in #8
